# Generated by Django 2.2.5 on 2019-09-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190905_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notifications', 'verbose_name_plural': 'Notifications'},
        ),
    ]
