# Generated by Django 2.2.5 on 2019-09-05 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190905_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='user',
        ),
    ]
